import type { Product } from '@/types';

// Unsplash image helper
const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?w=400&h=500&fit=crop&q=80`;

export const CATALOG: Product[] = [
  // ─── TOPS ───────────────────────────────────────────────────────────────────
  {
    id: 'uniqlo-supima-tee',
    title: 'Supima Cotton Crew Neck T-Shirt',
    brand: 'Uniqlo',
    price: 19.9,
    imageUrl: img('1521572163474-6864f9cf17ab'),
    productUrl: 'https://www.uniqlo.com/us/en/products/E449638-000',
    retailer: 'Uniqlo',
    colors: ['white', 'black', 'navy', 'grey', 'olive'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    category: 'tops',
    subcategory: 't-shirt',
    styles: ['minimalist', 'casual'],
    rating: 4.7,
    reviewCount: 2840,
    description: 'Ultra-soft Supima cotton tee with a clean, versatile silhouette.',
  },
  {
    id: 'nike-dri-fit-tee',
    title: 'Dri-FIT Legend 2.0 Training T-Shirt',
    brand: 'Nike',
    price: 35,
    imageUrl: img('1591047139829-d91aecb6caea'),
    productUrl: 'https://www.nike.com/t/dri-fit-legend-mens-training-t-shirt',
    retailer: 'Nike',
    colors: ['black', 'grey', 'navy', 'white'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    category: 'tops',
    subcategory: 't-shirt',
    styles: ['athletic', 'casual'],
    rating: 4.6,
    reviewCount: 1530,
    description: 'Sweat-wicking performance tee built for training and everyday wear.',
  },
  {
    id: 'levis-housemark-tee',
    title: "Levi's Original Housemark Graphic Tee",
    brand: "Levi's",
    price: 22,
    imageUrl: img('1618354691373-d851c5c3a990'),
    productUrl: 'https://www.levis.com/US/en_US/clothing/men/tops/t-shirts',
    retailer: "Levi's",
    colors: ['white', 'black', 'grey'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    category: 'tops',
    subcategory: 't-shirt',
    styles: ['casual'],
    rating: 4.4,
    reviewCount: 890,
    description: "Classic Levi's logo tee in premium cotton jersey.",
  },
  {
    id: 'ralph-lauren-polo',
    title: 'Classic Fit Mesh Polo Shirt',
    brand: 'Ralph Lauren',
    price: 98,
    imageUrl: img('1544716278-ca5e3f4abd8c'),
    productUrl: 'https://www.ralphlauren.com/polo-shirts',
    retailer: 'Ralph Lauren',
    colors: ['white', 'navy', 'green', 'light-blue', 'red'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    category: 'tops',
    subcategory: 'polo',
    styles: ['preppy', 'casual', 'formal'],
    rating: 4.8,
    reviewCount: 3200,
    description: 'Iconic mesh polo with embroidered pony logo — effortlessly versatile.',
  },
  {
    id: 'supreme-box-logo-tee',
    title: 'Box Logo Short Sleeve Tee',
    brand: 'Supreme',
    price: 48,
    imageUrl: img('1529720317453-c8da503f2051'),
    productUrl: 'https://www.supremenewyork.com/shop/all/tops-sweaters',
    retailer: 'Supreme',
    colors: ['white', 'black', 'red', 'navy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    category: 'tops',
    subcategory: 't-shirt',
    styles: ['streetwear'],
    rating: 4.5,
    reviewCount: 560,
    description: 'The definitive streetwear statement tee from downtown NYC.',
  },
  {
    id: 'cos-relaxed-shirt',
    title: 'Relaxed-Fit Organic Cotton Shirt',
    brand: 'COS',
    price: 55,
    imageUrl: img('1596755094514-f87e34085b2c'),
    productUrl: 'https://www.cos.com/en_usd/men/shirts.html',
    retailer: 'COS',
    colors: ['white', 'light-blue', 'cream', 'black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    category: 'tops',
    subcategory: 'shirt',
    styles: ['minimalist', 'casual', 'formal'],
    rating: 4.6,
    reviewCount: 720,
    description: 'Clean-cut organic cotton shirt with a relaxed drop-shoulder silhouette.',
  },
  {
    id: 'tommy-oxford-shirt',
    title: 'Regular Fit Oxford Button-Down Shirt',
    brand: 'Tommy Hilfiger',
    price: 69,
    imageUrl: img('1575311373937-040b8e1fd5b6'),
    productUrl: 'https://www.tommy.com/en/mens-shirts',
    retailer: 'Tommy Hilfiger',
    colors: ['white', 'blue', 'pink', 'navy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    category: 'tops',
    subcategory: 'shirt',
    styles: ['preppy', 'casual', 'formal'],
    rating: 4.5,
    reviewCount: 1100,
    description: 'Timeless Oxford button-down with signature Tommy flag embroidery.',
  },
  {
    id: 'nike-tech-fleece-crew',
    title: 'Tech Fleece Crew-Neck Sweatshirt',
    brand: 'Nike',
    price: 100,
    imageUrl: img('1591047139829-d91aecb6caea'),
    productUrl: 'https://www.nike.com/t/sportswear-tech-fleece-mens-crew-neck-sweatshirt',
    retailer: 'Nike',
    colors: ['black', 'dark-grey', 'navy', 'charcoal'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    category: 'tops',
    subcategory: 'sweatshirt',
    styles: ['athletic', 'casual', 'streetwear'],
    rating: 4.7,
    reviewCount: 2100,
    description: 'Lightweight fleece with spacer mesh construction for superior warmth and mobility.',
  },
  {
    id: 'carhartt-script-sweatshirt',
    title: 'Script Embroidery Sweatshirt',
    brand: 'Carhartt WIP',
    price: 75,
    imageUrl: img('1611312449408-fcece27cdbb7'),
    productUrl: 'https://www.carhartt-wip.com/collections/sweatshirts',
    retailer: 'Carhartt WIP',
    colors: ['grey', 'black', 'navy', 'green'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    category: 'tops',
    subcategory: 'sweatshirt',
    styles: ['workwear', 'casual', 'streetwear'],
    rating: 4.6,
    reviewCount: 940,
    description: 'Garment-dyed fleece sweatshirt with tonal Carhartt script embroidery.',
  },
  {
    id: 'off-white-diag-tee',
    title: 'Diagonal Stripe Print T-Shirt',
    brand: 'Off-White',
    price: 285,
    imageUrl: img('1469334031218-e382a71b716b'),
    productUrl: 'https://www.off---white.com/en-us/shopping/men/t-shirts',
    retailer: 'SSENSE',
    colors: ['white', 'black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    category: 'tops',
    subcategory: 't-shirt',
    styles: ['streetwear', 'luxury'],
    rating: 4.3,
    reviewCount: 210,
    description: 'Iconic diagonal stripe graphic on heavyweight cotton — a luxury streetwear staple.',
  },

  // ─── BOTTOMS ────────────────────────────────────────────────────────────────
  {
    id: 'levis-501-jeans',
    title: '501 Original Fit Jeans',
    brand: "Levi's",
    price: 89.5,
    imageUrl: img('1503341455253-b2e723bb3dbb'),
    productUrl: 'https://www.levis.com/US/en_US/clothing/men/jeans/501-original-fit-jeans',
    retailer: "Levi's",
    colors: ['medium-wash', 'dark-wash', 'black'],
    sizes: ['28', '29', '30', '31', '32', '33', '34', '36', '38'],
    category: 'bottoms',
    subcategory: 'jeans',
    styles: ['casual'],
    rating: 4.7,
    reviewCount: 5400,
    description: 'The original straight-leg jean since 1873 — a wardrobe non-negotiable.',
  },
  {
    id: 'uniqlo-slim-chinos',
    title: 'Slim-Fit Chino Trousers',
    brand: 'Uniqlo',
    price: 39.9,
    imageUrl: img('1441986300917-64674bd600d8'),
    productUrl: 'https://www.uniqlo.com/us/en/products/E449639-000',
    retailer: 'Uniqlo',
    colors: ['khaki', 'navy', 'olive', 'black', 'grey'],
    sizes: ['28', '29', '30', '31', '32', '33', '34', '36'],
    category: 'bottoms',
    subcategory: 'chinos',
    styles: ['minimalist', 'casual', 'formal'],
    rating: 4.6,
    reviewCount: 3100,
    description: 'Clean-fitting chinos in stretch cotton — goes with everything.',
  },
  {
    id: 'nike-tech-fleece-pants',
    title: 'Sportswear Tech Fleece Jogger Pants',
    brand: 'Nike',
    price: 110,
    imageUrl: img('1552902865-b72c031ac5ea'),
    productUrl: 'https://www.nike.com/t/sportswear-tech-fleece-mens-joggers',
    retailer: 'Nike',
    colors: ['black', 'dark-grey', 'navy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    category: 'bottoms',
    subcategory: 'joggers',
    styles: ['athletic', 'casual', 'streetwear'],
    rating: 4.8,
    reviewCount: 2900,
    description: 'Tapered tech fleece joggers with zippered cuffs and a modern silhouette.',
  },
  {
    id: 'apc-new-cure-jeans',
    title: 'New Cure Slim-Fit Raw Denim Jeans',
    brand: 'A.P.C.',
    price: 185,
    imageUrl: img('1503341455253-b2e723bb3dbb'),
    productUrl: 'https://www.apc.fr/en/mens/jeans/slim-fit-jeans',
    retailer: 'A.P.C.',
    colors: ['indigo', 'black'],
    sizes: ['28', '29', '30', '31', '32', '33', '34'],
    category: 'bottoms',
    subcategory: 'jeans',
    styles: ['minimalist', 'casual'],
    rating: 4.7,
    reviewCount: 830,
    description: 'Japanese raw denim that fades beautifully to your body over time.',
  },
  {
    id: 'carhartt-cargo-pants',
    title: 'Regular Cargo Pants',
    brand: 'Carhartt WIP',
    price: 120,
    imageUrl: img('1614632537197-38a17061c2bd'),
    productUrl: 'https://www.carhartt-wip.com/collections/cargo-pants',
    retailer: 'Carhartt WIP',
    colors: ['black', 'olive', 'brown', 'grey'],
    sizes: ['28', '29', '30', '31', '32', '33', '34', '36'],
    category: 'bottoms',
    subcategory: 'cargo',
    styles: ['workwear', 'casual', 'streetwear'],
    rating: 4.6,
    reviewCount: 1250,
    description: 'Utilitarian cargo pant in ripstop canvas — built for city and trail.',
  },
  {
    id: 'ralph-lauren-chinos',
    title: 'Stretch Classic Fit Chino Pants',
    brand: 'Ralph Lauren',
    price: 85,
    imageUrl: img('1544716278-ca5e3f4abd8c'),
    productUrl: 'https://www.ralphlauren.com/mens-pants-shorts',
    retailer: 'Ralph Lauren',
    colors: ['khaki', 'navy', 'grey', 'white'],
    sizes: ['28', '30', '32', '34', '36', '38'],
    category: 'bottoms',
    subcategory: 'chinos',
    styles: ['preppy', 'casual', 'formal'],
    rating: 4.5,
    reviewCount: 1600,
    description: 'Polished stretch chinos with a classic cut perfect for work or weekend.',
  },
  {
    id: 'hm-skinny-jeans',
    title: 'Skinny Jeans',
    brand: 'H&M',
    price: 29.99,
    imageUrl: img('1552902865-b72c031ac5ea'),
    productUrl: 'https://www2.hm.com/en_us/men/shop-by-product/jeans.html',
    retailer: 'H&M',
    colors: ['light-blue', 'dark-blue', 'black', 'grey'],
    sizes: ['28', '30', '31', '32', '33', '34', '36'],
    category: 'bottoms',
    subcategory: 'jeans',
    styles: ['casual'],
    rating: 4.2,
    reviewCount: 2100,
    description: 'Affordable skinny jeans with stretch denim for all-day comfort.',
  },
  {
    id: 'gymshark-shorts',
    title: 'Sport Training Shorts 5"',
    brand: 'Gymshark',
    price: 45,
    imageUrl: img('1506794778202-cad84cf45f1d'),
    productUrl: 'https://uk.gymshark.com/collections/mens-shorts',
    retailer: 'Gymshark',
    colors: ['black', 'grey', 'navy', 'white'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    category: 'bottoms',
    subcategory: 'shorts',
    styles: ['athletic'],
    rating: 4.7,
    reviewCount: 3400,
    description: 'Lightweight training shorts with built-in liner for unrestricted movement.',
  },

  // ─── SHOES ──────────────────────────────────────────────────────────────────
  {
    id: 'nike-air-max-270',
    title: 'Air Max 270',
    brand: 'Nike',
    price: 150,
    imageUrl: img('1542291026-7eec264c27ff'),
    productUrl: 'https://www.nike.com/t/air-max-270-mens-shoes',
    retailer: 'Nike',
    colors: ['black', 'white', 'multi', 'grey'],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    category: 'shoes',
    subcategory: 'sneakers',
    styles: ['athletic', 'casual', 'streetwear'],
    rating: 4.7,
    reviewCount: 4800,
    description: 'Iconic Air Max unit with max cushioning for all-day comfort.',
  },
  {
    id: 'adidas-ultraboost-22',
    title: 'Ultraboost 22 Running Shoe',
    brand: 'Adidas',
    price: 190,
    imageUrl: img('1542295669297-4d352b042bca'),
    productUrl: 'https://www.adidas.com/us/ultraboost-shoes',
    retailer: 'Adidas',
    colors: ['white', 'black', 'grey', 'blue'],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '12', '13'],
    category: 'shoes',
    subcategory: 'running',
    styles: ['athletic', 'casual'],
    rating: 4.8,
    reviewCount: 6100,
    description: 'Responsive Boost midsole with a woven Primeknit upper — premium performance.',
  },
  {
    id: 'new-balance-574',
    title: '574 Classic Sneaker',
    brand: 'New Balance',
    price: 84.99,
    imageUrl: img('1606107557195-0e29a4b5b4aa'),
    productUrl: 'https://www.newbalance.com/pd/574-classic/ML574-V2.html',
    retailer: 'New Balance',
    colors: ['grey', 'navy', 'green', 'burgundy'],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    category: 'shoes',
    subcategory: 'sneakers',
    styles: ['casual', 'streetwear'],
    rating: 4.7,
    reviewCount: 3500,
    description: 'The heritage runner with ENCAP cushioning that defines retro-casual style.',
  },
  {
    id: 'vans-old-skool',
    title: 'Old Skool Skate Shoe',
    brand: 'Vans',
    price: 70,
    imageUrl: img('1595950653106-6c9ebd614d3a'),
    productUrl: 'https://www.vans.com/shop/old-skool',
    retailer: 'Vans',
    colors: ['black/white', 'navy/white', 'all-white', 'checkerboard'],
    sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '12', '13'],
    category: 'shoes',
    subcategory: 'sneakers',
    styles: ['casual', 'streetwear'],
    rating: 4.6,
    reviewCount: 5200,
    description: 'The iconic side stripe low-top — a timeless skate-meets-street classic.',
  },
  {
    id: 'converse-chuck-taylor',
    title: 'Chuck Taylor All Star Classic',
    brand: 'Converse',
    price: 65,
    imageUrl: img('1491553895911-0055eca6402d'),
    productUrl: 'https://www.converse.com/shop/chuck-taylor-all-star',
    retailer: 'Converse',
    colors: ['white', 'black', 'red', 'navy', 'natural'],
    sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '12', '13'],
    category: 'shoes',
    subcategory: 'sneakers',
    styles: ['casual', 'streetwear'],
    rating: 4.6,
    reviewCount: 8900,
    description: 'The all-time classic canvas hi-top — still relevant after 100+ years.',
  },
  {
    id: 'common-projects-achilles',
    title: 'Achilles Low Leather Sneaker',
    brand: 'Common Projects',
    price: 525,
    imageUrl: img('1525966222134-fcfa99b8ae77'),
    productUrl: 'https://www.commonprojects.com/collections/mens-footwear',
    retailer: 'SSENSE',
    colors: ['white', 'black', 'tan'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    category: 'shoes',
    subcategory: 'sneakers',
    styles: ['minimalist', 'luxury', 'casual'],
    rating: 4.9,
    reviewCount: 680,
    description: 'The ultimate minimalist white sneaker — made in Italy, unmatched in simplicity.',
  },
  {
    id: 'nike-dunk-low',
    title: 'Dunk Low Retro',
    brand: 'Nike',
    price: 110,
    imageUrl: img('1600269452121-4f2416e55c28'),
    productUrl: 'https://www.nike.com/t/dunk-low-retro-mens-shoes',
    retailer: 'Nike',
    colors: ['white/black', 'white/red', 'green', 'many-colorways'],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12', '13'],
    category: 'shoes',
    subcategory: 'sneakers',
    styles: ['casual', 'streetwear', 'athletic'],
    rating: 4.8,
    reviewCount: 9200,
    description: 'Back-to-basics b-ball DNA turned streetwear icon — hundreds of colorways available.',
  },
  {
    id: 'adidas-samba-og',
    title: 'Samba OG Sneaker',
    brand: 'Adidas',
    price: 100,
    imageUrl: img('1542295669297-4d352b042bca'),
    productUrl: 'https://www.adidas.com/us/samba-og-shoes',
    retailer: 'Adidas',
    colors: ['white/black/gum', 'black/white/gum', 'green'],
    sizes: ['6', '7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '12', '13'],
    category: 'shoes',
    subcategory: 'sneakers',
    styles: ['casual', 'streetwear', 'preppy'],
    rating: 4.8,
    reviewCount: 7400,
    description: "The '70s indoor soccer classic with a gum sole — today's most-coveted sneaker.",
  },
  {
    id: 'timberland-6inch-boot',
    title: '6-Inch Premium Waterproof Boot',
    brand: 'Timberland',
    price: 198,
    imageUrl: img('1606107557195-0e29a4b5b4aa'),
    productUrl: 'https://www.timberland.com/boots/mens-boots',
    retailer: 'Timberland',
    colors: ['wheat', 'black', 'dark-brown'],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '12', '13'],
    category: 'shoes',
    subcategory: 'boots',
    styles: ['casual', 'workwear', 'streetwear'],
    rating: 4.7,
    reviewCount: 4100,
    description: 'The original wheat nubuck boot — waterproof, rugged, and undeniably iconic.',
  },
  {
    id: 'dr-martens-1460',
    title: '1460 Original 8-Eye Boot',
    brand: 'Dr. Martens',
    price: 170,
    imageUrl: img('1595950653106-6c9ebd614d3a'),
    productUrl: 'https://www.drmartens.com/us/en/mens/boots',
    retailer: 'Dr. Martens',
    colors: ['black', 'cherry-red', 'dark-brown'],
    sizes: ['6', '7', '8', '9', '10', '11', '12', '13'],
    category: 'shoes',
    subcategory: 'boots',
    styles: ['casual', 'streetwear'],
    rating: 4.6,
    reviewCount: 3700,
    description: 'The original 8-eyelet boot with air-cushioned sole — a counter-culture icon.',
  },

  // ─── OUTERWEAR ──────────────────────────────────────────────────────────────
  {
    id: 'patagonia-better-sweater',
    title: 'Better Sweater Fleece Jacket',
    brand: 'Patagonia',
    price: 99,
    imageUrl: img('1529720317453-c8da503f2051'),
    productUrl: 'https://www.patagonia.com/product/better-sweater',
    retailer: 'Patagonia',
    colors: ['navy', 'grey', 'black', 'dark-teal'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    category: 'outerwear',
    subcategory: 'fleece',
    styles: ['casual', 'athletic'],
    rating: 4.8,
    reviewCount: 5100,
    description: 'Warm, cozy fleece jacket made from 100% recycled polyester — a sustainable classic.',
  },
  {
    id: 'north-face-venture-2',
    title: 'Venture 2 Waterproof Jacket',
    brand: 'The North Face',
    price: 99,
    imageUrl: img('1529720317453-c8da503f2051'),
    productUrl: 'https://www.thenorthface.com/en-us/mens/jackets-and-vests',
    retailer: 'The North Face',
    colors: ['black', 'navy', 'red', 'green'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    category: 'outerwear',
    subcategory: 'rain-jacket',
    styles: ['athletic', 'casual'],
    rating: 4.7,
    reviewCount: 3800,
    description: 'Waterproof, packable rain jacket with DryVent technology — pack and go anywhere.',
  },
  {
    id: 'levis-trucker-jacket',
    title: 'Trucker Denim Jacket',
    brand: "Levi's",
    price: 69.5,
    imageUrl: img('1551028719-00167b16eac5'),
    productUrl: 'https://www.levis.com/US/en_US/clothing/men/jackets-and-coats',
    retailer: "Levi's",
    colors: ['medium-wash', 'dark-wash', 'black', 'sherpa-lined'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    category: 'outerwear',
    subcategory: 'denim-jacket',
    styles: ['casual', 'streetwear'],
    rating: 4.7,
    reviewCount: 4300,
    description: 'The original trucker jacket since 1962 — endlessly stylish, built to last.',
  },
  {
    id: 'zara-wool-overcoat',
    title: 'Wool Blend Overcoat',
    brand: 'Zara',
    price: 149,
    imageUrl: img('1525507119028-ed4c629a60a3'),
    productUrl: 'https://www.zara.com/us/en/man-coats-l854.html',
    retailer: 'Zara',
    colors: ['camel', 'grey', 'navy', 'black'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    category: 'outerwear',
    subcategory: 'coat',
    styles: ['minimalist', 'formal', 'casual'],
    rating: 4.4,
    reviewCount: 1800,
    description: 'Clean-lined wool-blend overcoat that elevates any outfit from casual to sharp.',
  },
  {
    id: 'carhartt-detroit-jacket',
    title: 'Detroit Blanket Lined Duck Jacket',
    brand: 'Carhartt',
    price: 139,
    imageUrl: img('1614632537197-38a17061c2bd'),
    productUrl: 'https://www.carhartt.com/product/j001/mens-blanket-lined-duck-active-jacket',
    retailer: 'Carhartt',
    colors: ['brown', 'black', 'dark-brown'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    category: 'outerwear',
    subcategory: 'work-jacket',
    styles: ['workwear', 'casual'],
    rating: 4.8,
    reviewCount: 2700,
    description: 'Legendary blanket-lined duck work jacket — indestructible warmth and style.',
  },
  {
    id: 'nike-tech-woven-jacket',
    title: 'Sportswear Tech Woven Jacket',
    brand: 'Nike',
    price: 120,
    imageUrl: img('1515886657613-9f3515b0c78f'),
    productUrl: 'https://www.nike.com/t/sportswear-tech-woven-mens-jacket',
    retailer: 'Nike',
    colors: ['black', 'grey', 'olive'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    category: 'outerwear',
    subcategory: 'jacket',
    styles: ['athletic', 'casual', 'streetwear'],
    rating: 4.5,
    reviewCount: 940,
    description: 'Clean-cut woven jacket with side pockets and zip closure — sport meets style.',
  },
  {
    id: 'patagonia-nano-puff',
    title: 'Nano Puff Insulated Jacket',
    brand: 'Patagonia',
    price: 199,
    imageUrl: img('1515886657613-9f3515b0c78f'),
    productUrl: 'https://www.patagonia.com/product/nano-puff',
    retailer: 'Patagonia',
    colors: ['black', 'navy', 'red', 'blue'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    category: 'outerwear',
    subcategory: 'puffer',
    styles: ['casual', 'athletic'],
    rating: 4.9,
    reviewCount: 4600,
    description: 'Ultra-packable PrimaLoft insulation jacket — warmth without the bulk.',
  },
  {
    id: 'supreme-coaches-jacket',
    title: 'Lightweight Coaches Jacket',
    brand: 'Supreme',
    price: 148,
    imageUrl: img('1506794778202-cad84cf45f1d'),
    productUrl: 'https://www.supremenewyork.com/shop/all/jackets',
    retailer: 'Supreme',
    colors: ['black', 'navy', 'red', 'olive'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    category: 'outerwear',
    subcategory: 'coaches-jacket',
    styles: ['streetwear'],
    rating: 4.5,
    reviewCount: 380,
    description: 'Box logo coaches jacket in a packable ripstop nylon — streetwear essentials.',
  },

  // ─── ACCESSORIES ────────────────────────────────────────────────────────────
  {
    id: 'new-era-5950-cap',
    title: '59FIFTY Fitted Cap',
    brand: 'New Era',
    price: 39.99,
    imageUrl: img('1588850561407-ed78c282e89b'),
    productUrl: 'https://www.neweracap.com/collections/mens-fitted-caps',
    retailer: 'New Era',
    colors: ['navy', 'black', 'grey', 'many-teams'],
    sizes: ['6 7/8', '7', '7 1/8', '7 1/4', '7 3/8', '7 1/2', '7 5/8', '7 3/4'],
    category: 'accessories',
    subcategory: 'hat',
    styles: ['casual', 'streetwear', 'athletic'],
    rating: 4.7,
    reviewCount: 6200,
    description: 'The authentic fitted cap — worn by athletes and collectors worldwide.',
  },
  {
    id: 'rayban-wayfarer',
    title: 'Original Wayfarer Classic Sunglasses',
    brand: 'Ray-Ban',
    price: 183,
    imageUrl: img('1588850561407-ed78c282e89b'),
    productUrl: 'https://www.ray-ban.com/usa/sunglasses/wayfarer',
    retailer: 'Ray-Ban',
    colors: ['black', 'tortoise', 'havana'],
    sizes: ['one-size'],
    category: 'accessories',
    subcategory: 'sunglasses',
    styles: ['casual', 'preppy', 'minimalist'],
    rating: 4.8,
    reviewCount: 7100,
    description: 'The iconic acetate frame silhouette that has defined cool since 1956.',
  },
  {
    id: 'carhartt-watch-hat',
    title: 'Watch Hat Beanie',
    brand: 'Carhartt WIP',
    price: 30,
    imageUrl: img('1576566588028-4147f3842f27'),
    productUrl: 'https://www.carhartt-wip.com/collections/headwear',
    retailer: 'Carhartt WIP',
    colors: ['black', 'grey', 'navy', 'green', 'red'],
    sizes: ['one-size'],
    category: 'accessories',
    subcategory: 'beanie',
    styles: ['casual', 'workwear', 'streetwear'],
    rating: 4.7,
    reviewCount: 2300,
    description: 'Ribbed-knit acrylic beanie with a small Carhartt WIP label — always goes right.',
  },
];
